name: sui faucet

on:
  schedule:
    - cron: '*/15 * * * *'  # 每 15 分钟执行一次

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Run script
      run: |
        bash ./scripts/sui-faucet.sh
